version: '3'

volumes:
  database:

services:
  db:
    image: mariadb
    container_name: mymariadb
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=devices
      - MYSQL_USER=admin 
      - MYSQL_PASSWORD=123456

networks:
  default:
    external:
      name:  nginx-jenkins

