version: '3'

volumes:
  static:

services:
  django-python3:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: dp
    container_name: dp
    restart: always
    working_dir: /root/devices/deviceManagement 
    volumes:
      - static:/root/devices/deviceManagement/static
    ports:
      - 127.0.0.1:8000:8000
    command: /root/devices/deviceManagement/start.sh

  nginx:
      build:
        context: .
        dockerfile: compose/production/nginx/Dockerfile
      image: nginx-dp
      restart: always
      container_name: nginx-dp
      volumes:
        - static:/root/devices/deviceManagement/static
      ports:
        - 80:80

networks:
  default:
    external:
      name:  nginx-jenkins

