version: '3'

volumes:
  static:
  database:

services:
  django-python3:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: dp
    container_name: dp
    working_dir: /root/devices/deviceManagement 
    volumes:
      - database:/root/devices/deviceManagement/database
      - static:/root/devices/deviceManagement/static
    ports:
      - "8000:8000"
    command: /start.sh
  nginx:
      build:
        context: .
        dockerfile: compose/production/nginx/Dockerfile
      image: nginx-dp
      container_name: nginx-dp
      volumes:
        - static:/root/devices/deviceManagement/static
      ports:
        - "80:80"

networks:
  default:
    external:
      name:  nginx-jenkins

