# Generated by Django 3.1.4 on 2021-01-15 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_number', models.IntegerField(verbose_name='devices ID')),
                ('change_user', models.CharField(max_length=20, verbose_name='change username')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'db_table': 'historyuser',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='status name')),
                ('tag', models.CharField(max_length=5, verbose_name='tag')),
                ('update_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='update time')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial Number')),
                ('bcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Barcode')),
                ('po', models.CharField(blank=True, max_length=50, null=True, verbose_name='PO#')),
                ('actual_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='actual_user')),
                ('borrow_wwid', models.CharField(blank=True, max_length=50, null=True, verbose_name='borrow_wwid')),
                ('po_requestor', models.CharField(blank=True, max_length=50, null=True, verbose_name=' po_requestor')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='devices.status')),
                ('functeam', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functeam', to='devices.status')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='devices.status')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='devices.status')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='devices.status')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['update_at'],
            },
        ),
    ]
