# Generated by Django 3.1.4 on 2020-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='functeam',
            field=models.CharField(choices=[('1', 'Pnp'), ('2', 'Validation'), ('3', 'Automation'), ('4', 'Semi-Auto')], max_length=6, verbose_name='function team'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='location',
            field=models.CharField(choices=[('1', 'Open lab'), ('2', 'ISMP '), ('3', 'Office')], max_length=6, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='po',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PO#'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='rowner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='requestor(Owner)'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('u', 'In use'), ('d', 'Damage'), ('s', 'In Stock')], max_length=6, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='wwid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='BorrowWWID'),
        ),
    ]
