# Generated by Django 3.1.4 on 2021-01-05 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='status name')),
                ('tag', models.CharField(max_length=5, verbose_name='tag')),
                ('update_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='update time')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.RemoveField(
            model_name='devices',
            name='rowner',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='wwid',
        ),
        migrations.AddField(
            model_name='devices',
            name='actual_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='actual_user'),
        ),
        migrations.AddField(
            model_name='devices',
            name='borrow_wwid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='borrow_wwid'),
        ),
        migrations.AddField(
            model_name='devices',
            name='po_requestor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=' po_requestor'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='sn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='devices.status'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='functeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functeam', to='devices.status'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='devices.status'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='devices.status'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='devices.status'),
        ),
    ]
