# Generated by Django 3.1.4 on 2021-01-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20210105_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='functeam',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functeam', to='devices.status'),
        ),
    ]
