# Generated by Django 3.1.5 on 2021-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20210120_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='comments',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='comments'),
        ),
    ]
