# Generated by Django 3.1.5 on 2021-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20210127_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='actual_user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='actual_user'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='borrow_wwid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='borrow_wwid'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='po',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PO#'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='po_requestor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' po_requestor'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='actual_user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='change actual_user'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='bcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='change username'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='borrow_wwid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='change borrow_wwid'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='change category'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='change comments'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='change location'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='change project'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='change status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='status name'),
        ),
    ]
