# Generated by Django 2.2 on 2020-12-28 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20, verbose_name='Serial Number')),
                ('bcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Barcode')),
                ('category', models.CharField(choices=[('1', 'Host'), ('2', 'Server'), ('3', 'Switch'), ('4', 'SF100'), ('5', 'EM100'), ('6', 'Control box'), ('7', 'SF600'), ('8', 'KVM'), ('9', 'KVM Dongle'), ('10', 'ITP'), ('11', 'LAUTERBACH '), ('12', 'Loopback'), ('13', 'Banino Village '), ('14', 'Power Meter'), ('15', 'RSC2'), ('16', 'PDU'), ('17', 'SSD'), ('18', 'Network Card'), ('19', 'DIMM'), ('20', 'U-Disk'), ('21', 'HSBP'), ('22', 'Others')], max_length=6, verbose_name='category')),
                ('status', models.CharField(choices=[('u', 'In use'), ('d', 'Damage'), ('s', 'In Stock')], max_length=6, verbose_name='status')),
                ('project', models.CharField(choices=[('1', 'Purley-R'), ('2', 'Eagle Stream'), ('3', 'Whitley-PI'), ('4', 'Whitley-PV'), ('5', 'Cedar Island'), ('6', 'NPX-D'), ('7', 'NPX-SP'), ('8', 'DL Boost'), ('9', 'CLX-AP'), ('10', 'IPU')], max_length=6, verbose_name='project')),
                ('functeam', models.CharField(choices=[('1', 'Pnp'), ('2', 'Validation'), ('3', 'Automation'), ('4', 'Semi-Auto')], max_length=6, verbose_name='function team')),
                ('location', models.CharField(choices=[('1', 'Open lab'), ('2', 'ISMP '), ('3', 'Office')], max_length=6, verbose_name='location')),
                ('po', models.CharField(blank=True, max_length=20, null=True, verbose_name='PO#')),
                ('rowner', models.CharField(blank=True, max_length=20, null=True, verbose_name='requestor(Owner)')),
                ('wwid', models.CharField(blank=True, max_length=10, null=True, verbose_name='BorrowWWID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('update_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='update time')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['update_at'],
            },
        ),
    ]
