"""empty message

Revision ID: 55829db5e39d
Revises: 
Create Date: 2020-08-11 22:22:35.338721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55829db5e39d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spike_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=6), nullable=True),
    sa.Column('create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spike_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.Text(length=100), nullable=True),
    sa.Column('price', sa.String(length=12), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desc'),
    sa.UniqueConstraint('price')
    )
    op.create_index(op.f('ix_spike_product_name'), 'spike_product', ['name'], unique=True)
    op.create_table('spike_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('create', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spike_users_name'), 'spike_users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spike_users_name'), table_name='spike_users')
    op.drop_table('spike_users')
    op.drop_index(op.f('ix_spike_product_name'), table_name='spike_product')
    op.drop_table('spike_product')
    op.drop_table('spike_order')
    # ### end Alembic commands ###
